"""audit_logs (target, created_at desc, id desc) index

Revision ID: d30064ba5f9e
Revises: 457a6439e2aa
Create Date: 2026-05-09 19:17:50.768108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30064ba5f9e'
down_revision: Union[str, Sequence[str], None] = '457a6439e2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_target_created_id', 'audit_logs', ['target_user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_target_created_id', table_name='audit_logs')
    # ### end Alembic commands ###
