"""add active-pagination partial index, drop deleted_at index

Revision ID: d63e89fbfa88
Revises: be32ff1c8a4a
Create Date: 2026-05-09 13:05:03.026009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63e89fbfa88'
down_revision: Union[str, Sequence[str], None] = 'be32ff1c8a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.create_index('ix_users_active_pagination', 'users', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_active_pagination', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
